services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/certs:/etc/nginx/certs:ro
      - ./docker/nginx/vhost:/etc/nginx/vhost.d
    networks:
      - nginx-proxy

  app:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    restart: unless-stopped
    environment:
      - CONTAINER_ROLE=app
    volumes:
      - .:/var/www/laravel
      - ./storage:/var/www/laravel/storage
      - ./bootstrap/cache:/var/www/laravel/bootstrap/cache
    networks:
      - app-network
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=dind.test,api.dind.test
      - VIRTUAL_PORT=80
    volumes:
      - .:/var/www/laravel:ro
      - ./docker/nginx/conf/sites:/etc/nginx/conf.d:ro
    networks:
      - app-network
      - nginx-proxy
    depends_on:
      - app

  queue:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    restart: unless-stopped
    environment:
      - CONTAINER_ROLE=queue
    volumes:
      - .:/var/www/laravel
      - ./storage:/var/www/laravel/storage
      - ./bootstrap/cache:/var/www/laravel/bootstrap/cache
    networks:
      - app-network
    depends_on:
      - redis

  scheduler:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    restart: unless-stopped
    environment:
      - CONTAINER_ROLE=scheduler
    volumes:
      - .:/var/www/laravel
      - ./storage:/var/www/laravel/storage
      - ./bootstrap/cache:/var/www/laravel/bootstrap/cache
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - app-network
    command: redis-server --appendonly yes

  node:
    image: node:24-alpine
    working_dir: /var/www/laravel
    volumes:
      - .:/var/www/laravel
    profiles:
      - build

networks:
  app-network:
    driver: bridge
  nginx-proxy:
    external: true

volumes:
  redis-data:
    driver: local
